import React from 'react';
import LogOutButton from '../LogOutButton/LogOutButton';
import {useSelector} from 'react-redux';
import nodemailer from 'nodemailer';


function UserPage() {
  // this component doesn't do much to start, just renders some user reducer info to the DOM
  const user = useSelector((store) => store.user);

  //let transporter = nodemailer.createTransport(transport[, defaults])

  let transport = nodemailer.createTransport({
      host: "smtp.mailtrap.io",
      port: 2525,
      auth: {
        user: "1a2b3c4d5e6f7g", //generated by Mailtrap
        pass: "1a2b3c4d5e6f7g" //generated by Mailtrap
      }
    });
    let mailOptions = {
      from: '"Example Team" <from@example.com>',
      to: 'andyehrhardt@gmail.com',
      subject: 'Nice Nodemailer test',
      text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
      html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer'
    };
    
    const sendEmail = () => {
      transport.sendMail(data[mailOptions, callback])
      console.log("in send email")
    }

  return (
    <div className="container">
      <h2>Welcome, {user.username}!</h2>
      <p>Your ID is: {user.id}</p>
      <LogOutButton className="btn" />
      <button onClick={sendEmail}>Send Email</button>
    </div>
  );
}

// this allows us to use <App /> in index.js
export default UserPage;
